import React, { Component } from 'react'
import classes from './Project.module.css';
import ScrollAnimation from 'react-animate-on-scroll';
import "animate.css/animate.min.css";
import { GoProject } from 'react-icons/go'
import android from '../images/languages/android.jpg';
import css from '../images/languages/css1.jpg';
import html from '../images/languages/html.jpg';
import js from '../images/languages/js.jpg';
import kml from '../images/languages/kml.jpg';
import php from '../images/languages/php.jpg';
import python from '../images/languages/python.jpg';
import sql from '../images/languages/sql.jpg';
import GoogleEarthReport from '../docs/Google_Earth_Report.pdf'

class Project extends Component {
  render() {
    return (
      <div className={classes.box} id="project">
        <ScrollAnimation offset={0} initiallyVisible={true}>
          <h2 className={classes.heading}>PROJECTS</h2>
          <div className={classes.Project}>
            <ScrollAnimation offset={0} initiallyVisible={true}>
              <div className={classes.app}>
               <h3>Google Earth</h3>
                <p>
                    A course project where the main aim was to identify the location of endangered species,
                    and places in Brazil where deforestation is happening at an exponential rate. 
                    Lastly, I created markers based on temperature around the world for a specific date.
                </p>

                <p> 
                    <img src={kml}></img>
                    <img src={python}></img>
                </p>

                <a href={GoogleEarthReport} rel="opener noreferrer" target="_blank"> View Project Report <GoProject /></a>
              </div>
            </ScrollAnimation>
            <ScrollAnimation offset={0} initiallyVisible={true}>
              <div className={classes.web}>
              <h3>Android Studio Tic Tac Toe Game</h3>
                <p>
                    A simple Tic Tac Toe game using Android Studio
                </p>

                <p> 
                    <img src={android}></img>
                    <img src={html}></img>
                </p>

                <a href='https://github.com/vishal7313/python-proj/tree/main/blackjack' rel="opener noreferrer" target="_blank"> View Project <GoProject /></a>
              </div>
            </ScrollAnimation>
           
            <ScrollAnimation offset={0} initiallyVisible={true}>
              <div className={classes.other}>
              <h3>Android Guessing Game</h3>
                <p>
                    An android project to guess the number which is randomly generated by the program.
                </p>
                
                <p> 
                    <img src={android}></img>
                    <img src={html}></img>
                </p>

                <a href='https://github.com/vishal7313/python-proj/tree/main/blackjack' rel="opener noreferrer" target="_blank"> View Project <GoProject /></a>
              </div>
            </ScrollAnimation>

            <ScrollAnimation offset={0} initiallyVisible={true}>
              <div className={classes.app}>
              <h3>BlackJack Game</h3>
                <p>
                    A python project where I implemented the concept of BlackJack Card Game.
                    As of now, only one player can play with the computer. I am working on
                    making it a multiplayer game. 
                </p>

                <p> 
                    <img src={python}></img>
                </p>

                <a href="https://github.com/vishal7313/python-proj/tree/main/blackjack" rel="opener noreferrer" target="_blank"> View Project <GoProject /></a>
              </div>
            </ScrollAnimation>

            <ScrollAnimation offset={0} initiallyVisible={true}>
              <div className={classes.web}>
              <h3>Silent Auction</h3>
                <p>
                    In this python project, a concept of slient auction is implemented.
                    Multiple users can bid at the same time and the user with highest bid
                    will win the bid.
                </p>

                <p> 
                    <img src={python}></img>
                </p>

                <a href="https://github.com/vishal7313/python-proj/tree/main/silent_auction" rel="opener noreferrer" target="_blank"> View Project <GoProject /></a>
              </div>
            </ScrollAnimation>

            <ScrollAnimation offset={0} initiallyVisible={true}>
              <div className={classes.other}>
              <h3>Higher Lower Game</h3>
                <p>
                    Developed Higher Lower game concept.
                    In this there are two section and player has to compare if the
                    left section is higher or lower. If the user guess it right, then the game keeps on going
                    otherwise any wrong guess will result in end of the game.
                </p>

                <p> 
                    <img src={python}></img>
                </p>

                <a href="https://github.com/vishal7313/python-proj/tree/main/high_lower_number" rel="opener noreferrer" target="_blank"> View Project <GoProject /></a>
              </div>
            </ScrollAnimation>
          </div>
        </ScrollAnimation>
      </div>
    )
  }
}

export default Project;